import './index.css';
import React from 'react';
import typhinetLogoImg from '../../assets/img/logo-typhinet.png';

const ProjectPage = props => {
  return (
    <div className="project">
      <img className="logoImage" src={typhinetLogoImg} />
      <h2 style={{ marginBottom: 0 }}>About TyphiNET</h2>
      <p>
        TyphiNET is a multi-institutional global collaborative network. Our goal is to facilitate data sharing, and assist in removing barriers to the re-use of pathogen genomic data from both endemic surveillance projects, as well as those data routinely generated by public health reference laboratories, for global public health benefit.
      </p>
      <p>
        The TyphiNET online platform is designed to collate all available whole genome sequence (WGS) data from the bacterial pathogen Salmonella Typhi. As bacterial WGS data is uniquely enriched with many characteristics of the infecting pathogen, we aim to provide up to date global estimates of both antimicrobial resistance and circulating genotypes for S. Typhi. We aim to improve global typhoid fever surveillance in the short term, and to provide evidence to assist in the improvement of intervention strategies and treatment guidelines for this pathogen in the long term.
      </p>
      <p>
        TyphiNET is coordinated by Dr Zoe Dyson, Dr Louise Cerdeira and Prof Kat Holt. We are based at the Department of Infection Biology at the <a href="https://www.lshtm.ac.uk/" target="_blank">London School of Hygiene and Tropical Medicine</a>, as well as the Department of Infectious Diseases at <a href="https://www.monash.edu/medicine/ccs/infectious-diseases/home" target="_blank">Monash University</a>. For more information about Holt lab projects and members, please visit the <a href="https://holtlab.net/">Holt Lab website</a>.
      </p>
      <p>
        TyphiNET has received funding from the European Union's Horizon 2020 research and innovation programme under the Marie Skłodowska-Curie grant agreement TyphiNET No 845681. We are also grateful to the Wellcome Trust for support from their Open Research Fund programme (219692/Z/19/Z). Follow us on <a href="https://twitter.com/typhinet">Twitter</a>.
      </p>
      <h2 style={{ marginBottom: 0 }}>Genomic analysis framework:</h2>
      <p>
        TyphiNET utilises the <a href="https://github.com/katholt/genotyphi/">GenoTyphi</a> genotyping scheme, publised by <a href= "https://www.nature.com/articles/ncomms12827">Wong <i>et al.</i> 2016</a>, and discussed in this <a href="https://holtlab.net/2016/10/12/global-picture-typhoid/">blog post</a>.  Data are sourced monthly from the <a href="https://pathogen.watch/">Pathogenwatch</a> online data analysis platform described in this <a href="https://www.biorxiv.org/content/10.1101/2020.07.03.186692v1.abstract"> preprint </a>by Argimón <i>et al.</i> 2020.
      </p>
    </div>
  );
};

export default ProjectPage;